### ISSUE TITLE
"Home"-link broken

### ISSUE THREAD

**Issue by Maltimore** [conda-forge/zwatershed-feedstock#7]
The repository doesn't seem to be available at github.com/Turagalab/zwatershed anymore, but this location is still mentioned in the README. Does someone know where it went?
Edit: it's at https://github.com/jakirkham/zwatershed now

**Comment by jakirkham** [comment]
That's just a fork I made. It's not being updated or maintained.

**Comment by jakirkham** [comment]
@conda-forge/core, what do people think about just archiving this? It doesn't seem to be maintained for some time (outside of core doing work on it) and, as it uses Boost, it is included in those migrations. Thinking we can save ourselves some work here.

**Comment by xhochy** [comment]
👍

**Comment by jakirkham** [comment]
Ok going to go ahead and archive it. Explained this in issue ( https://github.com/conda-forge/zwatershed-feedstock/issues/18 ) as well.
